version: '2'

services:

  # pgadmin: interface for postgresql
  pgadmin:
    image: thajeztah/pgadmin4
    restart: unless-stopped
    ports:
      - '9080:80'

  postgres:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=mysupersecretpassword
      - POSTGRES_USER=dbadmin
