version: '2'

networks:
  vishy-metrics:
    driver: bridge
  vishy-kafka:
    driver: bridge
  vishy-postgres:
    driver: bridge
  vishy-admin:
    driver: bridge

services:

  vishy:
    container_name: vishy-server1
    build: dockerfiles/vishy
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9001:9001"
    links:
      - influxdb:influxdb
      - kafka:kafka
      - postgres:postgres
    volumes:
      - /var/log:/var/log
    depends_on:
      - vishyadmin
    networks:
      vishy-admin:
        aliases:
          - vishy
      vishy-metrics:
      vishy-kafka:
      vishy-postgres:
    environment:
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      INFLUXDB_NAME: "vishy"
      INFLUXDB_USER: "root"
      INFLUXDB_PASS: "root"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dbadmin
      POSTGRES_PASS: mysupersecretpassword
      POSTGRES_USER: dbadmin

  vishyadmin:
    container_name: vishy-admin1
    image: aetas/spring-boot-admin-docker:1.4.1
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      vishy-admin:
        aliases:
          - vishyadmin


  influxdb:
    extends:
      file: docker-compose-tick-common.yml
      service: influxdb
    container_name: vishy-influxdb1
    build: dockerfiles/influxdb
    networks:
      - vishy-metrics

  chronograf:
    extends:
      file: docker-compose-tick-common.yml
      service: chronograf
    container_name: vishy-chronograf1
    build: dockerfiles/chronograf
    networks:
      - vishy-metrics

  grafana:
    extends:
      file: docker-compose-tick-common.yml
      service: grafana
    container_name: vishy-grafana1
    build: dockerfiles/grafana
    depends_on:
      - influxdb
      - postgres
    links:
      - influxdb:influxdb
      - postgres:postgres
    networks:
      - vishy-postgres
      - vishy-metrics


  pgadmin:
    extends:
      file: docker-compose-postgres-common.yml
      service: pgadmin
    container_name: vishy-pgadmin1
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - vishy-postgres

  postgres:
    extends:
      file: docker-compose-postgres-common.yml
      service: postgres
    container_name: vishy-postgres1
    networks:
      - vishy-postgres


  zookeeper:
    container_name: vishy-zookeeper1
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - vishy-kafka

  kafka:
    container_name: vishy-kafka1
    image: wurstmeister/kafka:0.10.1.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      #KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vishy-kafka


  ## cadvisor: resource usage and performance of containers
  cadvisor:
    container_name: vishy-cadvisor1
    image: google/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8082:8080"
