spring.profiles.active: production

app.name: vishy-demo
app.description: a simple openmrc demo server

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.port: 9001
management.context-path: /actuator

# LOGGING
logging.path: ./var/log
logging.file: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO

vishy.metrics:
  enabled: true
  console: true

vishy.kafka:
  enabled: true
  brokers: ${KAFKA_HOST}:${KAFKA_PORT}

vishy.influxdb:
  enabled: true
  host: ${INFLUXDB_HOST}
  port: ${INFLUXDB_PORT}
  database: ${INFLUXDB_NAME}
  username: ${INFLUXDB_USER}
  password: ${INFLUXDB_PASS}
  skip-idle-metrics: true
  interval-in-seconds: 10

vishy.jdbc:
  enabled: false
  jdbcUrl: ${POSTGRES_URL}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASS}
  driverClassName: org.postgresql.Driver
  tableName: vishy_openmrc_request_test_table

vishy.segmentio:
  enabled: false
  write-key: my_segmentio_write_key

vishy.keenio:
  enabled: false
  project-id: my_keenio_project_id
  read-key: my_keenio_read_key
  write-key: my_keenio_write_key

